apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build
spec:
  workspaces:
  - name: workspace
  steps:
    - name: build
      image: docker
      script: |
        #!/bin/sh
        cd /workspace/workspace/
        until docker ps; do sleep 3; done;
        docker build -t test .
        echo "Successfully tagged"