apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: clone
spec:
  workspaces:
  - name: workspace
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/bash
        sleep 2
        git clone https://github.com/devkotakushal/PrivateBinPublicTest.git
        cd PrivateBinPublicTest
        git checkout test